---
abstract: 'Serve translated HTML from markdown files from document root with directory index'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Directory-Markdown
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Data::Section::Simple: 0
  Plack: 0
  Plack::App::DataSection: 0
  Text::Markdown: 0
  Text::Xslate: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Songmu/p5-Plack-App-Directory-Markdown.git
version: 0.03
